### PR TITLE
Feature/docroot change

### PR DESCRIPTION
**Pull request by thomscode**
Change name of `web` folder to `docroot` to be more compatible with defaults in local-dev tools.  Updated file paths in the following files:

* `composer.json`
* `.gitignore`
* `.travis.yml`
* `.codeclimate.yml`

Resolves issue #4

### CODE REVIEW

**Comment by thomscode** [comment]
This follows PR #8

**Comment by dmlb2000** [comment]
We should add a pre-commit configuration to manage the formatting of the yml/json/xml files that might be present in the repository. They will keep the diffs cleaner in the future. There are several checks that should be added, white space at end of line, new lines at end of file, etc. All of these have autofix options that would allow devs to keep consistent diffs for us to look at.

**Comment by thomscode** [comment]
Conflicts resolved

**Comment by dmlb2000** [comment]
Go forth and prosper!

**Review by dmlb2000 — COMMENTED** [review]
Why did composer.json change every line in the file? Usually this happens as a dos2unix line ending issue... We should add some `gitattributes` https://git-scm.com/docs/gitattributes to enforce git using particular line endings so cross platform development doesn't screw with the diffs.

**Comment by thomscode** [comment]
After you enabled the `pre-commit` it complained about the `composer.json` file's line endings and updated. This file is correct according to the `pre-commit` run.

**Comment by dmlb2000** [comment]
Python is platform agnostic and so is git, we need to add a gitattributes file to tell git what line endings git should commit those files as...

**Comment by thomscode** [comment]
I'll look at that and update

**Comment by thomscode** [comment]
`.gitattributes` file already existed inside the `docroot` folder. It was simply one level too deep. This is now at the root level of the repository. I verified it does work but the changes to `composer.json` still show, as they were made at some point.

This PR is ready for review.

**Review by dmlb2000 — APPROVED** [review]
That's fine by me.

**Pull request merged**
